[tools]
hugo-extended = 'latest'
node = 'latest'
go = 'latest'

[tasks.install]
description = "Install project dependencies"
run = "npm install"

[tasks.update]
description = "Update node dependencies and prepare package.hugo.json file"
run = ["npm update", "rm package.hugo.json", "hugo mod npm pack"]

[tasks.install-example-deps]
description = "Install example site dependencies"
depends = ["install"]
dir = "exampleSite"
run = ["hugo mod tidy", "hugo mod npm pack", "npm install"]

[tasks.build]
description = "Build example site"
depends = ["install-example-deps"]
dir = "exampleSite"
run = ["hugo --gc --minify"]

[tasks.lint]
description = "Run linters"
depends = ["install"]
run = "npm run lint"

[tasks.example-site]
description = "Run the example server"
depends = ["install-example-deps"]
dir = "exampleSite"
run = "hugo server -w"

[tasks.fix-security]
description = "Run npm audit fix"
run = "npm audit fix --force"
